### ISSUE TITLE
How does it compare to pytrilium?

### ISSUE THREAD

**Issue by CsatiZoltan** [Nriver/trilium-py#12]
What major differences could you list between trilium-py and [pytrilium](https://github.com/perfectra1n/pytrilium)?

**Comment by Nriver** [comment]
Trilium-py provides all the standard etapi feature plus extra feature like todo list manipulation and markdown note migration. All the features are listed in the [toc](https://github.com/Nriver/trilium-py#-table-of-contents). It should be easy to use my package by following the sample code in the document.

I try to keep the source code sturcture simple. Only [one main file](https://github.com/Nriver/trilium-py/blob/main/src/trilium_py/client.py) and [some utils](https://github.com/Nriver/trilium-py/tree/main/src/trilium_py/utils). The code is quite straight forward which should be easy to understand.

**Comment by CsatiZoltan** [comment]
Using trilium-py, can one write extensions to Trilium in Python instead of Javascript? Or only those features can be used that are exposed by ETAPI?

**Comment by Nriver** [comment]
Nope, it's limited to interacting with etapi.
