### ISSUE TITLE
Duplicate Journal Day  Note

### ISSUE THREAD

**Issue by jwhonce** [Nriver/trilium-py#13]
I am not sure this is a trilium-py or trilium sync server issue. Or, mine...

I wrote a script to query critical items from Jira and create TODO items for me on the Journal Day Note. The script works fine when the  Day note exists.

When it creates a new empty page (3am via cron) and  then I press the "Open Today's Journal Note" launcher (at 8am) the launcher creates a second note for the day... The note created by trilium-py has the TODO items and my Day template contents while the launcher note only has my "Day template" contents.

I am running a sync server (quadlet/podman) and the script is configured to run against that server. The launcher, of course, is run on my laptop. 

Is it "bad" style to call  the ETAPI endpoint ` refresh-note-ordering`  after creating the Day note? That is the only ETAPI endpoint that seems to push to clients. At least from the OpenAPI spec. Or, there appears to be `apiRoute(POST, '/api/sync/now'`

Homepage:	https://github.com/zadam/trilium
App version:	0.60.4
DB version:	214
Sync version:	29
Build date:	2023-06-19T23:26:50+02:00
Build revision:	5905950c17791ce0eb278e010c2c8b3450fdb447
Data directory:	.../.local/share/trilium-data
Image: docker.io/zadam/trilium:0.60.4

**Comment by Nriver** [comment]
Assume the script creates a day note with id1 which is saved in server.

If you click the today button before the client finish syncing, the client will create a new day note with id2, as it does not aware of the id1 note. Then, after the sync, client will have two notes of the same day with both id1 and id2.

If you could wait for the syncing to finish for few seconds, the client will recognize the id1 note and use it for the day button.

**Comment by jwhonce** [comment]
I have workflow that is working. I plan on  submitting a PR with a  new close() method to call `/api/sync/now` endpoint. If you have no objections.

**Comment by jwhonce** [comment]
Fixed #15
