### ISSUE TITLE
ModuleNotFoundError: No module named 'magic'

### ISSUE THREAD

**Issue by meichthys** [Nriver/trilium-py#2]
Running this package from pypi results in the error: `ModuleNotFoundError: No module named 'magic'`

It looks like there may have been a pull request that fixed this. Maybe you only need to re-deploy to pypi?

**Comment by Nriver** [comment]
Thanks for the notice. I've just uploaded a new package here https://pypi.org/project/trilium-py/0.6.3/

**Comment by meichthys** [comment]
Thanks! I'll give it a try 👍

**Comment by Nriver** [comment]
This should've been fixed.
