### ISSUE TITLE
Support for full-text search

### ISSUE THREAD

**Issue by kleutzinger** [Nriver/trilium-py#33]
It would be nice to be able to use trilium-py to search for strings inside of the notes.

https://github.com/zadam/trilium/wiki/Search

As described in the etapi spec here: https://github.com/zadam/trilium/blob/69b686ba3b345606947ff15e91fb03eb3b6d4656/src/etapi/etapi.openapi.yaml#L43-L63

**Comment by Nriver** [comment]
It's already supported in the `search_note`.

https://github.com/Nriver/trilium-py?tab=readme-ov-file#-search-note
