### ISSUE TITLE
Img tags without closing "/>"

### ISSUE THREAD

**Issue by alglez** [Nriver/trilium-py#36]
Hi,

again with importing img tags.  I'm still importing some md files and i found another issue (previous: #34) related with the regex expression. I still found some images that are not properly imported. That's because `img` tag not necessarily need a closing match `/>` and `>` is enough. This can be seen in the example from the [w3schools](https://www.w3schools.com/tags/tag_img.asp)

`<img src="img_girl.jpg" alt="Girl in a jacket" width="500" height="600">`

So, again, probably the regex expression should be better like this:

`        pat = '<img (.*?)/?>'`

So the `/` is optional.

**Comment by Nriver** [comment]
Yes, you are right. Just made an update. https://github.com/Nriver/trilium-py/releases/tag/v0.8.8
