### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation

### ISSUE THREAD

**Issue by marleixo** [Nriver/trilium-py#44]
Exception has occurred: ImportError
failed to find libmagic.  Check your installation

Mac M1 Pro
Tried with Python 3.9 and 3.12

Install all dependencies, and nothing.. this library just doesn't want to work :-\
I've already installed libmagic manually as well 

(.venv) ➜  trilium-py git:(main) ✗ pip3 install libmagic
Collecting libmagic
  Using cached libmagic-1.0.tar.gz (3.7 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: libmagic
  Building wheel for libmagic (pyproject.toml) ... done
  Created wheel for libmagic: filename=libmagic-1.0-py3-none-any.whl size=4269 sha256=7ca855ec088fe656c9b52badf276a9f7061e55b95a8394bde05d9eea37ff8aba
  Stored in directory: /Users/ITAleixoMa/Library/Caches/pip/wheels/f8/8a/32/b5e5458427778faf24ad32526c49e2dc5d20f32c96bf6ce236
Successfully built libmagic
Installing collected packages: libmagic
Successfully installed libmagic-1.0

**Comment by Nriver** [comment]
try python-magic

**Comment by marleixo** [comment]
I’ve commented all the lines where it was called and it worked, job done. It was a one time thing, so, thanks anyway

**Comment by dbakit** [comment]
I meet this error too, it's a problem of `python-magic`, see: [python-magic/issues/313](https://github.com/ahupp/python-magic/issues/313) . I fix this error by  `brew install libmagic`
