### ISSUE TITLE
[feature requests] Upload file

### ISSUE THREAD

**Issue by holoword** [Nriver/trilium-py#5]
Sounds like markdown import only process image, sometime the markdown file contain link to other file, which not upload in this script.

**Comment by Nriver** [comment]
Hi, I've never tried linking files in markdown notes. Would you tell me what software you are using and provide a sample md including the file?

**Comment by Nriver** [comment]
I tried to use [obsidian-export](https://github.com/zoni/obsidian-export) to convert obsidian vault to ordinary markdown as explained here https://github.com/Nriver/trilium-py#import-from-obsidian.

But your the file in your sample does not seem to be handled properly by the tool. The square brackets in file name is causing issues like https://github.com/zoni/obsidian-export/issues/14.

**Comment by holoword** [comment]
Sorry for the export problem and late reply. I'm experience a hard weekday. The obsidian example is just a toy and not self test.
Previously, I used Joplin which direct export markdown with file, you can try to upload.
In Monday, I have success write a function with process file upload, but currently I have no time to format it, maybe after I complete my lifework I have time.
[joplinExport.zip](https://github.com/Nriver/trilium-py/files/11122260/joplinExport.zip)

**Comment by BARaphael** [comment]
@Nriver Hi, since #11 has been merged, can you create a new release and update pypi?

**Comment by Nriver** [comment]
I was waiting for his next pr. I will make a release anyway.

**Comment by BARaphael** [comment]
> I was waiting for his next pr. I will make a release anyway.

Thanks

**Comment by Nriver** [comment]
Just pushed 0.7.5 to pypi

**Comment by holoword** [comment]
Sorry for the late, I'm currently prepare for job interview and too busy, may I have time next weekend!

**Comment by Nriver** [comment]
Good luck with your job interview.

**Comment by holoword** [comment]
I have finish code writing and function test. But I find some confused naming in API and parameter naming.

**Comment by Nriver** [comment]
Basically I'd write with snake_case. But when it comes to the parameters defined in etapi like `noteId`, https://github.com/zadam/trilium/blob/7fc2824325f6a6bcbbd2e18179d69dbd4ac65d09/src/etapi/notes.js#LL80C9-L80C9, I would prefer to use the same name even if it's camelCase not the snake_case.

**Comment by Nriver** [comment]
Implemented in 99d2197c42fffae4dea3f91d89246550a7440f7f
